### ISSUE TITLE
feature request: package for luarocks?

### ISSUE THREAD

**Issue by mrcjkb** [mfussenegger/nlua#1]
Hey :wave: 
Cool to see this published :smile: 

Would you be open to packaging this for luarocks?
I would gladly take over the task if you are.

I believe this could be very useful for [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) (a WIP plugin manager that uses luarocks to install plugins).

It could potentially use this to configure luarocks to use Neovim as the interpreter, preventing issues in case users have an unsupported Lua version installed.
I believe setting `LUA_BINDIR` should allow this to be used without copying the script to `/usr/bin`.

**Comment by mfussenegger** [comment]
> Would you be open to packaging this for luarocks?

Yes. PRs are welcome

**Comment by Freed-Wu** [comment]
Maybe you will be interested in [nvimp](https://github.com/wakatime/prompt-style.lua#neovim)

![Screenshot_20241212_030817](https://github.com/user-attachments/assets/aed2ba39-d45f-48a8-8765-7790824b6e08)
It provides a REPL for neovim, should be useful to debug some lua code in neovim. You can use `$VIMRC` to config its behavior.
